name: CI + CD
'on':
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'
  workflow_dispatch: null
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to qa and qa test
    if: github.event_name == 'pull_request'
    needs:
      - Build
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: http://qa.progressmagic.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployStaging:
    name: Deploy to Uat and Test Uat
    if: github.event.ref == 'refs/heads/uat'
    needs:
      - Build
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: http://uat.progressmagic.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    needs:
      - Build
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://app.progressmagic.com
    steps:
      - name: Deploy
        run: echo I am deploying!