name: Rollback to Specific Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to rollback to'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://app.progressmagic.com
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/tags/${{ github.event.inputs.tag }}

    - name: npm install
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_PROD }}
        aws-region: ${{ secrets.REGION_PROD }}

    - name: Create JSON File
      working-directory: ./
      env:
        SECRET_JSON_VALUE: ${{ secrets.SECRET_JSON_VALUE }}
      run: |
        echo -n "$SECRET_JSON_VALUE" > int-progress-magic-dev-firebase-adminsdk.json

    - name: Fetch ECS task definition
      run: aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_PROD }} --query taskDefinition > task-definition.json

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ACCOUNT_ID_PROD }}.dkr.ecr.${{ secrets.REGION_PROD }}.amazonaws.com/${{ secrets.ECR_REPO_NAME_PROD }}:latest

    - name: Update and register ECS task definition with new image
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ secrets.CONTAINER_NAME_PROD }}
        image: ${{ secrets.ACCOUNT_ID_PROD }}.dkr.ecr.${{ secrets.REGION_PROD }}.amazonaws.com/${{ secrets.ECR_REPO_NAME_PROD }}:latest

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ secrets.ECS_SERVICE_NAME_PROD }}
        cluster: ${{ secrets.ECS_CLUSTER_NAME_PROD }}
        wait-for-service-stability: true