# name: CI/CD Pipeline on Tag Creation from Main Branch

# on:
#   push:
#     tags:
#       - '*'

# jobs:
#   check-main-branch:
#     runs-on: ubuntu-latest
#     outputs:
#       proceed: ${{ steps.verify_tag.outputs.proceed }} 
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Verify tag is on main branch
#         id: verify_tag
#         run: |
#           TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
#           MAIN_COMMIT=$(git rev-parse origin/main)
#           if [ "$TAG_COMMIT" == "$MAIN_COMMIT" ]; then
#             echo "Tag is on main branch. Proceeding with deployment."
#             echo "::set-output name=proceed::yes"
#           else
#             echo "Tag is not on main branch. Skipping deployment."
#             echo "::set-output name=proceed::no"
#           fi

#   DeployStaging:
#     name: Deploy to Uat and Test Uat (Staging)
#     needs: check-main-branch
#     if: ${{ needs.check-main-branch.outputs.proceed == 'yes' }}
#     runs-on: ubuntu-latest
#     environment:
#       name: Staging to uat
#       url: http://uat.progressmagic.com
#     steps:
#       - name: Deploy
#         run: echo I am deploying!

#   build-and-deploy:
#     needs: [check-main-branch, DeployStaging]
#     if: ${{ needs.check-main-branch.outputs.proceed == 'yes' }}
#     runs-on: ubuntu-latest
#     environment:
#       name: Production
#       url: http://app.progressmagic.com
#     steps:
#       - name: Deploy
#         run: echo I am deploying!
